main: net.pravian.forcetime.ForceTime
authors: [Prozza]
name: ForceTime
version: 2.2
description: Set the time or weather, permanently
commands:
  forcetime:
    usage: /<command> <world> <off | day | night>
    description: Set the time, permanently.
  forceweather:
    usage: /<command> <world> <off | sun | rain | thunder>
    description: Set the weather, permanently.